services:
  web:
    image: laravel-vue-starter-kit
    build:
      context: .
      dockerfile: ./.docker/php/dev.Dockerfile
    volumes:
      - .:/var/www:cached
    depends_on:
      - db
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravelvuestarterkit
      - DB_USERNAME=laravelvuestarterkit
      - DB_PASSWORD=laravelvuestarterkit
    entrypoint: ["/usr/local/bin/entrypoint.sh"]
    command: ["php-fpm"]
    networks:
      - laravel

  nginx:
    image: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - .:/var/www:ro
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web

  db:
    image: mysql:8.1
    restart: always
    ports:
        - 3306:3306
    volumes:
        - .docker/db/data:/var/lib/mysql
        - .docker/logs:/var/log/mysql
        - .docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
        - .docker/db/sql:/docker-entrypoint-initdb.d
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: laravelvuestarterkit
        MYSQL_USER: laravelvuestarterkit
        MYSQL_PASSWORD: laravelvuestarterkit
    networks:
      - laravel

  vite:
    image: node:20
    working_dir: /var/www
    volumes:
      - .:/var/www
    command: bash -c "npm install && npm run dev"
    ports:
      - 5173:5173
    networks:
      - laravel

  queue:
    image: laravel-vue-starter-kit
    build:
      context: .
      dockerfile: ./.docker/php/prod.Dockerfile
    volumes:
      - .:/var/www
    depends_on:
      - web
      - db
    command: php artisan queue:work
    networks:
      - laravel
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravelvuestarterkit
      - DB_USERNAME=laravelvuestarterkit
      - DB_PASSWORD=laravelvuestarterkit

networks:
  laravel:
    driver: bridge
